### ISSUE TITLE
Intégration numérique

### ISSUE THREAD

**Issue by claudiosousa** [mathintro/deuxiemeannee#16]
Pour les formules d'intégration numérique 2.42 et 2.43, il me semble que la somme devrait aller jusqu'à _N-1_ (en lieu de jusqu'à _N_). Ceci car en sommant pour _i_ allant de _0_ à _N_, allors cela correspond à l'integration de _a_ jusqu'à _b+delta x_ (et non pas de _a_ à _b_ comme désiré).

Si @mathintro est d'accord, je peux soummetre un pull request

**Comment by mathintro** [comment]
@mathintro est d'accord.

**Comment by claudiosousa** [comment]
Adressée par #17
