### ISSUE TITLE
Calcul d'erreur pour les coéficients de fourier pour des sinaux ou b0 != 0

### ISSUE THREAD

**Issue by claudiosousa** [mathintro/deuxiemeannee#18]
Je me demande si ses équations 4.63, 4.67 et 4.68 sont justes pour des signaux avec moyenne différente 0. Est-ce qu'il ne faudrait pas soustraire la moyenne su signal à f(t)? Example pour 4.67: b_j = 2/T \int_0^T cos(j\omega t)(f(t)-b_0/2)

**Comment by mathintro** [comment]
Essayez d'intégrer juste cos(j*omega*t)*b_0/2 entre 0 et T. Et la réponse apparaîtra.

**Comment by claudiosousa** [comment]
Le coefficient qui ne dépend pas de la variable integrée disparaît...
