### ISSUE TITLE
Calcul de série de fourier pour des functions avec b0 != 0

### ISSUE THREAD

**Issue by claudiosousa** [mathintro/deuxiemeannee#20]
L'équation 4.62 fait la somme pour des j in 0..infinity.
Pour j = 0, a0 * sin(0) = 0, et b0 * cos(0) = b0

Equation 4.69 dit que b0 = 2 * moyenne de f(t), pour t in 0..T
Dans ce cas, pour b0!=0, nous avons comme valeur continue de la function, ou offset vertical de la moyene, de 2 * la moyenne. Ceci est incorrect car on ne devrait offseter la function de la valeur de la moyenne.

D'autres auteurs font le choix de avoir la somme pour j in 1..infinity et avoir b0/2 additioné séparément. (ie b0/2 + sum_j=1^inifinty a*sin+b*cos). Cette approche résout le problème, bien qu'elle soit légèrement moins élégante, et moins bien connéecte avec 4.57, 4.58, 4.59

**Comment by mathintro** [comment]
Je ne suis pas d'accord. Pour tous les termes où on a une moyenne non-nulle ce terme disparaît à l'exception pour j!= 0:

b_j = int_0^T f(t)*cos(omega*j*t) dt.

si f(t)=b_0/2+g(t) on a que (g(t) est la fonction f(t) à laquelle on a enlevé la moyenne)

b_j = int_0^T (b_0/2+g(t))*cos(omega*j*t) dt.
      = int_0^T b_0/2*cos(omega*j*t) dt + int_0^T g(t)*cos(omega*j*t) dt.
      =                        0                       +  int_0^T g(t)*cos(omega*j*t) dt.

Löe zéro vient de la périodicité de cos(j*omega*t) et que b_0 est une constante

On a donc que les b_j pour g(t) sont les mêmes que ceux pour f(t) à part quand j=0.

**Comment by claudiosousa** [comment]
Mais justement, ma remarque concerne b_j, pour j=0.

Example, si f(t)= sin(omega t) + 1, 

eq. 4,62 dit que f(t)=sum_j=0_^infty (a_j sin(j omega t))+b_j cos(j omega t))

Pour notre f(t), nous avons donc que:
f(t) = a_1 sin(1 omega t) + b_0 cos(0 omega t)
     = sin(omega t) + b_0

Et eq 4.69 dit que:
b_0 = 2/T int_0^T f(f)
donc, 
b_0 = 2/T int_0^T (sin(omega t)+1)
       = 2/T * 1
       = 2 , puisque T=1

Nous avons donc que
f(t) = sin(omega t) + 2, ce qui est faux! car sin(omega t) + 1 != sin(omega t) + 2

Par contre, f(t)= **b_0/2** + sum_j=**1**_^infty (a_j sin(j omega t))+b_j cos(j omega t)) permet d'obtenir le bon résultat:
f(t) = 2/2 + sin(omega t)

**Comment by mathintro** [comment]
Aaaaaaah. J'ai enfin compris quel est votre problème. Il ne s'agit pas d'enlever ou d'ajouter la moyenne. Effectivment. Il y a un facteur 1/2 en trop. Je l'avais laissé de côté exprès pour éviter les confusions. Mais vous avez 100% raison. Avec cette définition le facteur 2 est en trop. Et la phrase qui explique ce qui se passe est très mal écrite dans le cours. Je vais reformuler tout ça pour l'année prochaine. Merci.

**Comment by mathintro** [comment]
Pour terminer l'omission dans la dérivation qui pose problème est que int_0^Tcos^2(j*omega*t)dt = T/2 si j!= 0 et T si j=0. Je trouve cette partie assez compliquée et j'ai décidé de plutôt me concentrer sur le raisonnamenent de minimsation de l'erreur plutôt que sur ce détail.

**Comment by claudiosousa** [comment]
Je comprends tout a fait, il sera compliqué d'introduire cela a cet endroit dans complexifier la compréhension par le lecteur.
